// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModelbureauetDB.Models;

namespace ModelbureauetDB.Migrations
{
    [DbContext(typeof(ModelbureauetDBContext))]
    [Migration("20190103093614_initial2")]
    partial class initial2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ModelbureauetDB.Models.Jobs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comments");

                    b.Property<string>("CustomerName");

                    b.Property<bool>("IsPlanned");

                    b.Property<string>("Location");

                    b.Property<int>("NumberOfDays");

                    b.Property<int>("NumberOfModels");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("Id");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("ModelbureauetDB.Models.Model", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("Comments");

                    b.Property<string>("HairColor");

                    b.Property<int>("Height");

                    b.Property<string>("Name");

                    b.Property<int>("PhoneNumber");

                    b.Property<int>("Weight");

                    b.HasKey("Id");

                    b.ToTable("Model");
                });
#pragma warning restore 612, 618
        }
    }
}
